### ISSUE TITLE
Debian - new nuc - crash at OS installation

### ISSUE THREAD

**Issue by pierrickmolera** [seapath/build_debian_iso#115]
![logs_20240812](https://github.com/user-attachments/assets/1e058ab4-0a83-4393-8c69-c842a4d28a0b)
That happens after install Seapath install on a new nuc.

Seapath build debian iso installer has been updated and when I list from another machine I can see from the /lib/firmware folder all missing .bin files that are mentionned from this log
So the reason should not be missing .bin file in fact

My problem with this new nuc, from the Bios I'm not able to disable some option as Wifi, bluethoot etc ...

On another side I've sucessfully installed public Debian OS (not Seapath) with a connection to the online apt
So from Debian OS I can see there is an additional firmware by listing all :  firmware-sof-signed
add this one into our SEAPATH_HOST file would it be enough ?

**Comment by insatomcat** [comment]
it's worth a shot, but since it's very specific to your setup you may try to add this to `usercustomization/package_config/USERCUSTOMIZATION`:
```
PACKAGES install-norec
firmware-sof-signed
```

**Comment by pierrickmolera** [comment]
thanks @insatomcat it's working now.
usercustomization is a convenient way to manage this kind of issue.

**Comment by insatomcat** [comment]
happy you like it :)
