### ISSUE TITLE
Build fail during nfsroot creation

### ISSUE THREAD

**Issue by Paullgk** [seapath/build_debian_iso#81]
Hello,
I encountered this issue during an iso build:

```
dracut: Generating /boot/initrd.img-6.1.0-18-amd64
'/ext/nfsroot/boot/vmlinuz-6.1.0-18-amd64' -> '/ext/srv/tftp/fai/vmlinuz-6.1.0-18-amd64'
'/ext/nfsroot/boot/initrd.img-6.1.0-18-amd64' -> '/ext/srv/tftp/fai/initrd.img-6.1.0-18-amd64'
'/ext/nfsroot/usr/lib/PXELINUX/lpxelinux.0' -> '/ext/srv/tftp/fai/pxelinux.0'
TFTP environment prepared. Enable DHCP and start the TFTP daemon on root /ext/srv/tftp/fai.

ERROR: Do not use systemd inside the nfsroot.
Log file written to /var/log/fai/fai-make-nfsroot.log
Log file written to /var/log/fai/fai-make-nfsroot.log and /ext/nfsroot/var/tmp
ERROR when calling fai-make-nfsroot.
Log file written to /var/log/fai/fai-setup.log
ERROR: 9
```

I am using commit `71fc4a16c6930b7fb4c736a91408e8181d7e6e4d` (main branch). It seems that this issue has been introduced by commit `03c1e16ad9b011552c31c25df7adc63a284c2713`. 
If I checkout my workdir on commit `5376150e4f639175fe557fc9e67cf3dba4a1a886` I can successfully build an image.

Thanks in advance.

**Comment by insatomcat** [comment]
can you please delete and rebuild your fai docker image?

**Comment by Paullgk** [comment]
Thanks, didn't saw the modification added to the Dockerfile by the latest commit. Fixed by regenerating a new image.
