### ISSUE TITLE
last FAI version (6.2) impacts Intel Nuc installation

### ISSUE THREAD

**Issue by pierrickmolera** [seapath/build_debian_iso#88]
I've updated my build_debian_iso to the last version and the installation doesn't work anymore with my test machines (Intel Nuc)
After several validations, add firmware, librairies etc...,
I've identified the FAI upgrade impacts my Seapath installation on Intel Nuc :
https://github.com/seapath/build_debian_iso/blob/5f0d9b1a89773d7b4db9394d0e1b7d62ce76b56d/Dockerfile#L2-L3

The second and default option is endless rebooting, behind several firmware issues, FAI server with or without dhcp is failing too.
Here attached file with logs
![PXL_20240308_161403426](https://github.com/seapath/build_debian_iso/assets/73014265/8990034a-9cde-43c4-a7db-c5111f1d5261)

To fix those issue I came back to the commit: 5376150e4f639175fe557fc9e67cf3dba4a1a886 and now I'm able to install seapath again

**Comment by insatomcat** [comment]
Hello,

Can you test with branch "test1" ?
Also, it's very important you remove and rebuild your docker image when you move to an FAI 6.2 commit.

Thanks.

**Comment by pierrickmolera** [comment]
ok I will test branch test1
That I'm doing everytime now I'm recreating USB key : 
- docker compose down
- docker rmi fai
- docker system prune    => time to time that removes residual container/image cache if wrong build_iso execution

So even if I removed fai image I got the issue

**Comment by insatomcat** [comment]
The log show a problem with the partitionning task.
unfortunately, we can't see the exact problem since it's hidden with all the dmesg logs.
Can you look in the fai.log file and identify what's the actual partitionning problem ?

**Comment by insatomcat** [comment]
solved by #89
