### ISSUE TITLE
Blocked startup with a new Nuc : 13 Pro : 13ANH170000-321T

### ISSUE THREAD

**Issue by pierrickmolera** [seapath/build_debian_iso#98]
Hello I've tried to install seapath on a new Nuc (13 Pro : 13ANH170000-321T)  but startup failed.
The first time it was due to Wifi driver : 
![PXL_20240517_170837412](https://github.com/seapath/build_debian_iso/assets/73014265/da0abf68-d422-4f7b-8309-7a099765bbf6)

I disabled the option from Bios and at the next startup it goes further, but blocked again and without message : 
![PXL_20240517_171337500](https://github.com/seapath/build_debian_iso/assets/73014265/f2495005-2ec6-450f-b6c8-00dd524461b8)

Have you some tips on how to continue to investigate ?

**Comment by insatomcat** [comment]
Hello,
It's quite hard to help you since it seems very dependant on your hardware.
This build_debian_iso is "just" a convenient way to install debian, I guess what you can try is install debian with the standard debian installer (minimal install).
Either you have the same problem and we can rule out an issue with seapath (this will be between nuc and debian), or you don't and then we can be certain it comes with some of the customization we have in our installer (like a missing needed package maybe?).

**Comment by pierrickmolera** [comment]
Hello thanks for your advice.

I have installed Debian without any update from the Internet and it was blocked too.
![PXL_20240520_115026915](https://github.com/seapath/build_debian_iso/assets/73014265/6c165af6-1e60-4ed1-864c-4872f32a733a)

But after I installe DEbian again and give the possibility to update firmware from the Internet and now I can start my Debian on this Nuc.

Firstable is there any way to get the failed instructions during startup of Seapath (debian) by activating a mode as "safe mode" (sans échec)
And from the successfully Debian installation, is there a way to get all upadted firmware during the connection to the Internet and get the list of downloaded binaries ?

**Comment by insatomcat** [comment]
To boot your failing install you can try adding "init=/bin/bash" to your linux cmdline in grub.

To identify the possible missing package you can try "dpkg -l | grep firmware" to list all the packages including the firmware keyword on both installs, and try to add packages in srv_fai_config/package_config/SEAPATH_HOST and rebuild your iso.

Or you can try rebuilding with firmware-linux-nonfree, firmware-linux-free, firmware-misc-nonfree, firmware-amd-graphics and see it it helps.

**Comment by pierrickmolera** [comment]
thanks, I will identify additional packages by comparing with Seapath installation ones and see how to add them.

**Comment by pierrickmolera** [comment]
I've checked dpkg and firmwares from seapath installation

```
virtu@node1:~$ dpkg -l | grep firmware
ii  amd64-microcode                      3.20230808.1.1~deb12u1         amd64        Processor microcode firmware for AMD CPUs
ii  intel-microcode                      3.20231114.1~deb12u1           amd64        Processor microcode firmware for Intel CPUs
ii  ipxe-qemu                            1.0.0+git-20190125.36a4c85-5.1 all          PXE boot firmware - ROM images for qemu
ii  ovmf                                 2022.11-6+deb12u1              all          UEFI firmware for 64-bit x86 virtual machines
```

and from the debian installation on the new Nuc
```
root@debian:/home/pierrick# dpkg -l | grep firmware
ii  firmware-linux-free          20200122-1                     all          Binary firmware for various drivers in the Linux kernel
ii  firmware-misc-nonfree        20230210-5                     all          Binary firmware for various drivers in the Linux kernel
ii  intel-microcode              3.20231114.1~deb12u1           amd64        Processor microcode firmware for Intel CPUs
```

So I've added into SEAPATH_HOST file : 
 - firmware-linux-free
- firmware-misc-nonfree

and Nuc is starting well.

I have a question about those both packages, is it adding many dependencies and breaking the security parts ?
So from my side I will continue and execute Ansible tasks now for a standalone installation.
Thanks again Florent

**Comment by insatomcat** [comment]
Hello,
I'm glad you solved it. I don't think it comes with any dependency and I also don't think it will impacts security.
You are good to go.
Some tests will fail if you try to run the cukinia-tests (because the tested list of packages is [hardcoded](https://github.com/seapath/cukinia-tests/blob/6947ad56035dfc9aea34626f1802269c6584d5ee/cukinia/common_security_tests.d/apt.conf.j2)) but it's easily fixed if you want to pass those tests.

I'm closing the issue.

**Comment by eroussy** [comment]
Just one quick question 
Should we add these firmware by default on build_debian_iso ?
In order for it to boot on these type of machine.

**Comment by insatomcat** [comment]
Certainly, I don't see why not. It would easy a new user in, and the user can still choose to uninstall the extra firmware packages if he/she likes.
We need to also change cukinia-tests accordingly.

**Comment by insatomcat** [comment]
my bad, firmware-linux-nonfree has a dependency on firmware-linux-free, and this is already [allowed by cukinia-tests](https://github.com/seapath/cukinia-tests/blob/6947ad56035dfc9aea34626f1802269c6584d5ee/cukinia/common_security_tests.d/apt.conf.j2#L40)
So we can safely add firmware-misc-nonfree to SEAPATH_HOST package_config (please check https://github.com/seapath/build_debian_iso/pull/99)
